### Traer tareas
GET http://localhost:3000/api/foro

### Crear tarea
POST http://localhost:3000/api/foro
Content-Type: application/json

{
    "title":"Titulo",
    "query":"Consulta",
    "imageUrl":"www.google.com"
}
### Actualizar tarea
PUT http://localhost:3000/api/foro
Content-Type: application/json

{
    "title":"Cambio de titulo",
    "query":"Hola soy una modificación",
    "imageUrl":"www.gmail.com"
}


### Eliminar tarea
DELETE http://localhost:3000/api/foro
